
- name: install usbutils
  apt: name=usbutils state=present
  become: true

#- name: add vagrant to dialup-account
#  user: name=vagrant groups=dialup
#  register: added_group
#  become: true

#- name: issue newgroup
#  cmd: newgroup dialup
#  when: added_group|success

- name: give usb access to all users
  template: src=50-embedded_devices.rules dest=/etc/udev/rules.d/50-embedded_devices.rules mode=0644
  notify: Restart udev
  become: true
